# The name of the App #
name: Pets
# Some general settings for the project #
options: 
    createIntermediateGroups: true
    indentWidth: 4
    tabWidth: 4
    bundleIDPrefix: "com.seven" 
    xcodeVersion: "13.4"
targets:
    Pets:
        type: application
        platform: iOS
        # iOS version
        deploymentTarget: "15.0"
        sources:
            - path: Pets

        # settings
        settings:
            ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
            base:
                CURRENT_PROJECT_VERSION: 0
                MARKETING_VERSION: 1.0.0
                PRODUCT_BUNDLE_IDENTIFIER: com.seven.pets
        # info.plist
            info: 
                path: Sources/Pets/Info.plist



