# The name of the App #
name: Pets
# Some general settings for the project #
options: 
    createIntermediateGroups: true
    indentWidth: 4
    tabWidth: 4
    bundleIDPrefix: "com.seven" 
    xcodeVersion: "13.4"
    postGenCommand: pod install

targets:
    Pets:
        type: application
        platform: iOS
        # iOS version
        deploymentTarget: "15.0"
        sources:
            - path: Pets

        # settings
        settings:
            ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
            base:
                CURRENT_PROJECT_VERSION: 0
                MARKETING_VERSION: 1.0.0
                # Bundle ID
                PRODUCT_BUNDLE_IDENTIFIER: com.seven.pets
                # Team ID
                DEVELOPMENT_TEAM: "NMM9F9QK67"
                # capability
                CODE_SIGN_ENTITLEMENTS: Pets/Pets.entitlements

        # info.plist
            info: 
                path: Sources/Pets/Info.plist
        scheme:
            gatherCoverageData: true
    PetsTests:
        type: bundle.unit-test
        platform: iOS
        deploymentTarget:
            iOS: "15.0"
        sources:
            - path: PetsTests
        dependencies:
            - target: Pets
